### ISSUE TITLE
Custom CSS...?

### ISSUE THREAD

**Issue by EC-O-DE** [romanyanke/tumblr-tag-cloud#1]
Hey, any idea why custom CSS such as
<---------EXAMPLE---------------->
```
a div.tumblr-tag-list :link,
a div.tumblr-tag-list :visited {
  background-color: #f44336;
  color: white;
  padding: 14px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

a div.tumblr-tag-list :hover,
a div.tumblr-tag-list :active {
  background-color: red;
}
```
<--------------------QUIT------------------------>

doesn't work?

Doesn't work either when set like this:
`a div.tumblr-tag-list:link,`

**Comment by romanyanke** [comment]
looks like you mean
```
.tumblr-tag-list a:link {…}
.tumblr-tag-list a:visited {…}
```

**Comment by EC-O-DE** [comment]
`.tumblr-tag-list a:link, a:visited {  background-color: #f44336;
  color: white;
  padding: 14px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

.tumblr-tag-list a:hover, a:active {
  background-color: red;
}`

:)

**Comment by EC-O-DE** [comment]
Oh no, it's not working!
I have the cloud on a  custom layout page, so maybe custom CSS no function there?
But then again general css (no pseudo) does CSSify the tag cloud..
Any ideas?

**Comment by romanyanke** [comment]
1. Fix your selectors. They should be not just

`.tumblr-tag-list a:link, a:visited {…}`

but repeat `.tumblr-tag-list` in each selector:

✅ `.tumblr-tag-list a:link, .tumblr-tag-list a:visited {…}`. 

2. Next respect the order of pseudo selectors. See more https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links#Styling_some_links

Let me know if it works

**Comment by EC-O-DE** [comment]
Thanks I'll try that!
BTW just checking,, does this look valid?
```
#tumblr-tag-list {
    color: white;
    font-size: 15px;
}
```

**Comment by EC-O-DE** [comment]
WOW it's working!
This finally did it! Thanks for the help!!!!
`#tumblr-tag-list a:link, .tumblr-tag-list a:visited {
  background-color: #347153;
  color: white;
  border: 2px solid green;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

#tumblr-tag-list a:hover, .tumblr-tag-list a:active {
 background-color: #00264b;
 color: green;
}`

**Comment by romanyanke** [comment]
glad to help
